version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" 
  - package-ecosystem: "maven"
    directory: "/auth-context-java"
    schedule:
      interval: "weekly" 
  - package-ecosystem: "maven"
    directory: "/authz-queryplan-jpa"
    schedule:
      interval: "weekly" 
  - package-ecosystem: "maven"
    directory: "/openapi-spring-boot-starter"
    schedule:
      interval: "weekly" 
  - package-ecosystem: "pip"
    directory: "/auth-context-python"
    schedule:
      interval: "weekly" 
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly" 
