services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    privileged: true
    environment:
      CLAUDE_CONFIG_DIR: /home/l64user/.claude
    volumes:
      - ..:/workspaces/labs64.io-commons
      - maven-repository:/home/l64user/.m2/repository
      - vscode-extensions:/home/l64user/.vscode-server/extensions
      - vscode-server-data:/home/l64user/.vscode-server/data
      - codex-data:/home/l64user/.codex
      - claude-data:/home/l64user/.claude
      - copilot-data:/home/l64user/.copilot
      - docker-data:/var/lib/docker

volumes:
  maven-repository:
    name: labs64io-maven-repository
  vscode-extensions:
    name: labs64io-vscode-extensions
  vscode-server-data:
  codex-data:
  claude-data:
  copilot-data:
  docker-data:
