name: l64-auth-context - Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        required: true
        description: The release version X.Y.Z

jobs:
  release:
    name: Release ${{ github.event.inputs.release-version }} / Java 17
    runs-on: ubuntu-latest
    env:
      RELEASE_WORK_DIR: checkout-for-release

    steps:
    - name: Checkout the sources
      uses: actions/checkout@v4
      with:
        path: ${{ env.RELEASE_WORK_DIR }}
        ssh-key: '${{ secrets.REPO_SSH_KEY }}'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Prepare git config
      run: |
        cd ${{ env.RELEASE_WORK_DIR }}
        git config user.name "GitHub Actions Bot"
        git config user.email "netlicensing@labs64.com"

    - name: Prepare maven settings.xml
      run: |
        mkdir -p ~/.m2
        cat << EOF >~/.m2/settings.xml
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>labs64-nexus</id>
              <username>\${{ secrets.NEXUS_USER }}</username>
              <password>\${{ secrets.NEXUS_PASS }}</password>
            </server>
            <server>
              <id>ossrh</id>
              <username>\${{ secrets.OSS_USER }}</username>
              <password>\${{ secrets.OSS_PASS }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Import GPG key
      run: echo "${{ secrets.GPG_KEY }}" | base64 -d | gpg --pinentry-mode loopback --passphrase "${{ secrets.GPG_KEY_PASS }}" --import

    - name: Set Release Version
      run: |
        cd ${{ env.RELEASE_WORK_DIR }}/auth-context-java
        mvn versions:set -DnewVersion=${{ github.event.inputs.release-version }} -DgenerateBackupPoms=false

    - name: Release to Maven Central staging and Nexus
      run: |
        cd ${{ env.RELEASE_WORK_DIR }}/auth-context-java
        mvn -s ~/.m2/settings.xml -B \
            clean deploy \
            -P release \
            -Dgpg.passphrase=${{ secrets.GPG_KEY_PASS }}

    - name: Commit and tag version bump
      run: |
        cd ${{ env.RELEASE_WORK_DIR }}
        git add auth-context-java/pom.xml
        git commit -m "chore: bump version to ${{ github.event.inputs.release-version }}"
        git tag -a v${{ github.event.inputs.release-version }} -m "Release ${{ github.event.inputs.release-version }}"
        git push origin main
        git push origin v${{ github.event.inputs.release-version }}
